### ISSUE TITLE
Make neighbors persistent

### ISSUE THREAD

**Issue by yet-another-account** [akashgoswami/ipm#11]
Maybe save nodes to file and on startup, call addNeighbor for each?

**Comment by brunoamancio** [comment]
I would add them to the --config file.ini
That would be awesome

**Comment by akashgoswami** [comment]
I can understand the usability of this but it violates the design principle. The config.ini is usually read only and should be modified only by the IRI or the user. The right thing to do is to add a new feature request with IRI which updates config.ini in case of peer update request via API. 

IOTA-PM will only manage its own config file at the moment.
