### ISSUE TITLE
ENOENT when installing with npm -i -g iota-pm (running Debian jessie)

### ISSUE THREAD

**Issue by vhaasteren** [akashgoswami/ipm#14]
[ vhaasteren myhostname ~ ] sudo npm i -g iota-pm
[sudo] password for vhaasteren:
npm ERR! Error: ENOENT, lstat '/usr/local/lib/node_modules/iota-pm/node_modules/async/everySeries.js'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.16.0-4-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "i" "-g" "iota-pm"
npm ERR! cwd /home/vhaasteren
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! path /usr/local/lib/node_modules/iota-pm/node_modules/async/everySeries.js
npm ERR! fstream_path /usr/local/lib/node_modules/iota-pm/node_modules/async/everySeries.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (evalmachine.<anonymous>:107:15)
npm ERR! Error: ENOENT, lstat '/usr/local/lib/node_modules/iota-pm/node_modules/restler/test/restler.js'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.16.0-4-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "i" "-g" "iota-pm"
npm ERR! cwd /home/vhaasteren
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! path /usr/local/lib/node_modules/iota-pm/node_modules/restler/test/restler.js
npm ERR! fstream_path /usr/local/lib/node_modules/iota-pm/node_modules/restler/test/restler.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (evalmachine.<anonymous>:107:15)
npm ERR! Error: ENOENT, lstat '/usr/local/lib/node_modules/iota-pm/node_modules/minimist/test/bool.js'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.16.0-4-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "i" "-g" "iota-pm"
npm ERR! cwd /home/vhaasteren
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! path /usr/local/lib/node_modules/iota-pm/node_modules/minimist/test/bool.js
npm ERR! fstream_path /usr/local/lib/node_modules/iota-pm/node_modules/minimist/test/bool.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (evalmachine.<anonymous>:107:15)
npm ERR! 404 Not Found
npm ERR! 404
npm ERR! 404 'types/express' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 It was specified as a dependency of 'express-basic-auth'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

npm ERR! System Linux 3.16.0-4-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "i" "-g" "iota-pm"
npm ERR! cwd /home/vhaasteren
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! code E404
npm ERR! Error: ENOENT, lstat '/usr/local/lib/node_modules/iota-pm/node_modules/socket.io/History.md'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.16.0-4-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "i" "-g" "iota-pm"
npm ERR! cwd /home/vhaasteren
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! path /usr/local/lib/node_modules/iota-pm/node_modules/socket.io/History.md
npm ERR! fstream_path /usr/local/lib/node_modules/iota-pm/node_modules/socket.io/History.md
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (evalmachine.<anonymous>:107:15)
npm ERR! Error: ENOENT, lstat '/usr/local/lib/node_modules/iota-pm/node_modules/gentelella/build/css/custom.css'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.16.0-4-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "i" "-g" "iota-pm"
npm ERR! cwd /home/vhaasteren
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! path /usr/local/lib/node_modules/iota-pm/node_modules/gentelella/build/css/custom.css
npm ERR! fstream_path /usr/local/lib/node_modules/iota-pm/node_modules/gentelella/build/css/custom.css
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (evalmachine.<anonymous>:107:15)
npm ERR! Error: ENOENT, lstat '/usr/local/lib/node_modules/iota-pm/node_modules/express/History.md'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.16.0-4-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "i" "-g" "iota-pm"
npm ERR! cwd /home/vhaasteren
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! path /usr/local/lib/node_modules/iota-pm/node_modules/express/History.md
npm ERR! fstream_path /usr/local/lib/node_modules/iota-pm/node_modules/express/History.md
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (evalmachine.<anonymous>:107:15)
npm ERR! Error: ENOENT, lstat '/usr/local/lib/node_modules/iota-pm/node_modules/iota.lib.js/dist/iota.js'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.16.0-4-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "i" "-g" "iota-pm"
npm ERR! cwd /home/vhaasteren
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! path /usr/local/lib/node_modules/iota-pm/node_modules/iota.lib.js/dist/iota.js
npm ERR! fstream_path /usr/local/lib/node_modules/iota-pm/node_modules/iota.lib.js/dist/iota.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (evalmachine.<anonymous>:107:15)
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/vhaasteren/npm-debug.log
npm ERR! not ok code 0

**Comment by akashgoswami** [comment]
Looks like the issue related with npm. Can't help much here.
