### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by brunoamancio** [akashgoswami/ipm#16]
I'm getting the following error on the browser's console:

`Property or method "address" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option.`

It happens in vue.js.  On the part of the code bellow:

```
    if (config.warnHandler) {
      config.warnHandler.call(null, msg, vm, trace);
    } else if (hasConsole && (!config.silent)) {
      console.error(("[Vue warn]: " + msg + trace));
    }
```

I only open the page and on the updates I get the message.

**Comment by akashgoswami** [comment]
Thanks. Fixed it.

**Comment by brunoamancio** [comment]
What is the commit number?

**Comment by akashgoswami** [comment]
https://github.com/akashgoswami/ipm/commit/0c02be30a08f7bc7482f3ace2078f02261e12804
