### ISSUE TITLE
iota-pm.service file

### ISSUE THREAD

**Issue by opel22** [akashgoswami/ipm#28]
I have no Exec in the folder "/usr/bin/" called iota-pm, probably therefor I don't get the PM working with "systemctl daemon-reload", however, if I start using "iota-pm -i http://127.0.0.1:14800 -p 127.0.0.1:8888" the PM works fine. Sorry, I have very limited Linux know-how, but perhaps you can help?
thx!

**Comment by akashgoswami** [comment]
You don't need to use the service if you dont want to. Running via command line is also ok.
