### ISSUE TITLE
Request Error: COMMAND removeNeighbors is not available on this node

### ISSUE THREAD

**Issue by opel22** [akashgoswami/ipm#29]
... and the same when trying to add neighbors - any hint? Thx!

**Comment by MClarkDev** [comment]
https://iota.stackexchange.com/questions/351/why-can-i-not-run-commands-on-a-node

Was IRI launched with `--remote-limit-api` flag and any commands to restrict? Or do you have `REMOTE_LIT_API` defined in the ini file?

This error comes from IRI, not IPM.

**Comment by opel22** [comment]
Hi Matt, unfortunately I cannot check your link -> To log in, you must have commited to the Area 51 site proposal and **_received the invitation email_.** 

My iota.ini has REMOTE_LIMIT_API="removeNeighbors, addNeighbors, interruptAttachingToTangle, attachToTangle" - should be ok, right?

**Comment by akashgoswami** [comment]
removeNeighbors, addNeighbors are required for the IOTA-PM to work. This will be addressed in readonly mode where these API are not needed.
