### ISSUE TITLE
"Manual" for iota-pm ...

### ISSUE THREAD

**Issue by opel22** [akashgoswami/ipm#33]
Hi akashgoswami
can you (or someone else) clarify what the different transactions numbers (all, random, new, invalid and sent) mean? Or point me to where I can get some information about them?
Thx a lot!
kind regards
opel22

**Comment by akashgoswami** [comment]
Hi Opel22, 
IOTA PM calls following API for this information
https://iota.readme.io/reference#getneighborsactivity

**Comment by crwatkins** [comment]
@opel22 Take a look [here](https://github.com/akashgoswami/ipm/pull/34#issue-279219799) where I add a tiny bit more information to the counters.
