### ISSUE TITLE
IOTA-PM does not install/start correctly..

### ISSUE THREAD

**Issue by lukas-osterheider** [akashgoswami/ipm#35]
Hi,

i get this error message after trying to start "iota-pm -i .......":
/usr/bin/env: »node“: Datei oder Verzeichnis nicht gefunden

It says: "node" file or directory not found.

Can you please help me?

**Comment by akashgoswami** [comment]
Hi, 

You dont have nodejs installed or it is not in your path. Please install nodejs first and make sure node -v command works fine on your system.

**Comment by lukas-osterheider** [comment]
Hi,
thanks for the answer!
I installed node.js and no i came to this step:
XXXXXXXXX:~# iota-pm -i http://127.0.0.1:14265 -p 127.0.0.1:8888
Serving IOTA peer dashboard at http://127.0.0.1:8888
Unable to locate any previous tag file at /root/iota-pm.conf

After this nothing happens. Do i need to write any other configs or so?

**Comment by lukas-osterheider** [comment]
Ahh, i see that this is only a warning.

**Comment by lukas-osterheider** [comment]
Now I fixed it.
I had to right the servername as incoming connection:
iota-pm -i http://localhost:14265 -p v220171253004XXXXXXX:8888
