### ISSUE TITLE
Nginx reverse proxy

### ISSUE THREAD

**Issue by rexberg** [akashgoswami/ipm#36]
Hi,

Would it be possible to run a reverse proxy through Nginx? This means that we could setup authentication and SSL.

Something like this:

```
...
location / {
		proxy_pass http://127.0.0.1:8888;
	        proxy_http_version 1.1;
	        proxy_set_header Upgrade $http_upgrade;
	        proxy_set_header Connection 'upgrade';
	        proxy_set_header Host $host;
	        proxy_cache_bypass $http_upgrade;
	}
...
```

Best regards,
Markus

**Comment by ixidion** [comment]
Should be not that hard. I will create some docker container for that the next days. At the moment my workaround is, to bind the API_port to localhost and then I'm doing a Portforwarding via SSH.

**Comment by rexberg** [comment]
Yes. The code I posted works with nginx as a reverse proxy. I will close this issue.
