### ISSUE TITLE
Changing node addresses

### ISSUE THREAD

**Issue by christiangrieger** [akashgoswami/ipm#37]
I just noticed many times now that after some time the ip that got added changes to another one for some node. So the nodes still sync and are connected but the address changed and the name is unknown so i do not know anymore who it is.

Any idea?

**Comment by akashgoswami** [comment]
This is clearly a problem with IRI itself. Could you please take a curl snapshot of following command https://iota.readme.io/reference#getneighborsactivity
Before and after this problem and raise a case with IRI github?

**Comment by christiangrieger** [comment]
Uh i can try that but i am not so good with linux stuff

**Comment by ixidion** [comment]
You can configure IRI with: DNS_REFRESHER_ENABLED=false to prevent reverse DNS lookups
