### ISSUE TITLE
Let's combine iota-pm and iota-node!

### ISSUE THREAD

**Issue by nazarimilad** [akashgoswami/ipm#39]
Hey, thanks for your great work. 

Currently iota-pm can't manage the IRI configuration file. [I just made a script](https://github.com/nazarimilad/iota-node) which not only
installs and runs the IRI but it also manages the IRI configuration file.

So I was wondering, if you could make use of my script in your dashboard in the following way for example:

```
EventHandler buttonAddNeighbor(Event e) {
    ...
    iota-node --add-neighbor e.getAddress();
}
```

It's just an example.

**Comment by akashgoswami** [comment]
IPM doesn't modify the IRI config and there is no plan to do that in future. Best would be to keep these two projects seperate.
