### ISSUE TITLE
Duplication of nodes

### ISSUE THREAD

**Issue by dkarelov** [akashgoswami/ipm#7]
Case:
Node owner provided DNS A, which resolves to IP XX
However, XX also resolved back to DNS B by IRI
Dashboard first shows A, then flags it as red, then adds B, so there are two nodes referring to the same node XX, but one is working and the other is not

**Comment by akashgoswami** [comment]
Unfortunately there is no easy way to resolve it as we depend upon IOTA IRI APIs.
