### ISSUE TITLE
Make the chart timeframe longer and ability to remove lines

### ISSUE THREAD

**Issue by dkarelov** [akashgoswami/ipm#8]
Now it provides only short-term view of the node activity. 24h timeframe would be much more useful.
Also would be great to have an ability to turn off some of the lines - e.g. total transactions or sent transactions - the most useful one is "new transactions" and this is one I would like to monitor

**Comment by akashgoswami** [comment]
The lines can be removed now by clicking on the legend icon. The timeframe can be adjusted from the command line option in iota-pm 
iota-pm -r (time interval in seconds)
